name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
      - main

defaults:
  run:
    working-directory: ./docs

env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}} # store the github enverment in there

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checking@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
